<a href="https://colab.research.google.com/github/Ravitejasabbu/2303A51164_B18-/blob/main/LAB%202.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
marks = np.array([
[85, 78, 92],
[76, 88, 80],
[90, 94, 89],
[65, 70, 72],
[88, 82, 95]
])
print("Student Marks:")
print(marks)
#Average, Min, Max marks
print("Average marks of each student:", np.mean(marks, axis=1))
print("Minimum marks of each student:", np.min(marks, axis=1))
print("Maximum marks of each student:", np.max(marks, axis=1))
print("Average marks in each subject:", np.mean(marks, axis=0))
print("Minimum marks in each subject:", np.min(marks, axis=0))
print("Maximum marks in each subject:", np.max(marks, axis=0))
#Marks of 2nd student
print("Marks of Student 2:", marks[1, :])
#Students scoring above 80 in any subject
print("Students scoring above 80 in any subject:")
print(marks[marks > 80])
print("Analysis:")
print("1. Student 3 performed best overall with high marks in all subjects.")
print("2. Student 4 needs improvement as scores are the lowest across subjec.")
print("3. Subject 3 shows consistently high performance among students.")

Student Marks:
[[85 78 92]
 [76 88 80]
 [90 94 89]
 [65 70 72]
 [88 82 95]]
Average marks of each student: [85.         81.33333333 91.         69.         88.33333333]
Minimum marks of each student: [78 76 89 65 82]
Maximum marks of each student: [92 88 94 72 95]
Average marks in each subject: [80.8 82.4 85.6]
Minimum marks in each subject: [65 70 72]
Maximum marks in each subject: [90 94 95]
Marks of Student 2: [76 88 80]
Students scoring above 80 in any subject:
[85 92 88 90 94 89 88 82 95]
Analysis:
1. Student 3 performed best overall with high marks in all subjects.
2. Student 4 needs improvement as scores are the lowest across subjec.
3. Subject 3 shows consistently high performance among students.


In [2]:
import pandas as pd
data = {
"ID": [101, 102, 103, 104, 105],
"Name": ["Alice", "Bob", "Charlie", "David", "Eva"],
"Department": ["HR", "IT", "Finance", "IT", "HR"],
"Salary": [48000, 60000, 55000, 45000, 70000]
}
df = pd.DataFrame(data)
print("Original Employee DataFrame:\n", df)
# employees with salary > 50,000
high_salary = df[df["Salary"] > 50000]
print("\nEmployees with Salary > 50,000:\n", high_salary)
#salary in descending order
sorted_df = df.sort_values(by="Salary", ascending=False)
print("\nEmployees Sorted by Salary (Descending):\n", sorted_df)
#Bonus (10% of salary)
df["Bonus"] = df["Salary"] * 0.10
print("\nDataFrame with Bonus Column:\n", df)
#Calculate total salary expense including bonus
df["TotalPay"] = df["Salary"] + df["Bonus"]
total_expense = df["TotalPay"].sum()
print("\nTotal Salary Expense (with Bonus):", total_expense)

Original Employee DataFrame:
     ID     Name Department  Salary
0  101    Alice         HR   48000
1  102      Bob         IT   60000
2  103  Charlie    Finance   55000
3  104    David         IT   45000
4  105      Eva         HR   70000

Employees with Salary > 50,000:
     ID     Name Department  Salary
1  102      Bob         IT   60000
2  103  Charlie    Finance   55000
4  105      Eva         HR   70000

Employees Sorted by Salary (Descending):
     ID     Name Department  Salary
4  105      Eva         HR   70000
1  102      Bob         IT   60000
2  103  Charlie    Finance   55000
0  101    Alice         HR   48000
3  104    David         IT   45000

DataFrame with Bonus Column:
     ID     Name Department  Salary   Bonus
0  101    Alice         HR   48000  4800.0
1  102      Bob         IT   60000  6000.0
2  103  Charlie    Finance   55000  5500.0
3  104    David         IT   45000  4500.0
4  105      Eva         HR   70000  7000.0

Total Salary Expense (with Bonus): 305800.0